#!/usr/bin/env python3
"""Renders prover_pod_unit.rendered.yaml dynamically from config.toml proving_pod profiles."""

import argparse
import os
import sys

try:
  import tomllib  # Python 3.11+
except ImportError:
  try:
    import tomli as tomllib
  except ImportError:
    import toml as tomllib


def tree_depth(n, radix):
  """ceil(log_radix(n)): number of node levels above N leaves.

  Mirrors `tree_depth` in bench/src/bin/prover_node.rs. Computed iteratively to
  avoid float rounding hazards near exact powers (e.g. log2(8) == 3 exactly).
  """
  if radix < 2:
    raise ValueError("radix must be >= 2")
  if n <= 1:
    return 0
  depth = 0
  span = 1  # radix**depth
  while span < n:
    span *= radix
    depth += 1
  return depth


def nodes_at_level(n, radix, level):
  """ceil(n / radix**level): node count at a 1-indexed tree level.

  Mirrors `nodes_at_level` in bench/src/bin/prover_node.rs. The root level always
  has exactly one node.
  """
  if level < 1:
    raise ValueError("tree levels are 1-indexed")
  divisor = radix ** level
  return max((n + divisor - 1) // divisor, 1)


def padded_leaf_count(n):
  """Smallest power of two >= n (with pad(0)=pad(1)=1).

  Mirrors `padded_leaf_count` in bench/src/transport/gating.rs
  (`n.next_power_of_two()`, N in {0,1} -> 1). The padded perfect binary reduction
  tree spans leaf interval [0, P-1]; the reduction ROOT proof covers exactly that
  interval.
  """
  if n <= 1:
    return 1
  # Smallest power of two >= n: 2->2, 4->4, 5->8, 125->128, 500->512.
  # (n-1).bit_length() gives ceil(log2(n)) for n>=2.
  return 1 << (n - 1).bit_length()


def root_proof_name(fold_strategy, depth, leaf_count):
  """(#321 Phase 9) The filename of the ROOT proof the pipeline commits, by
  strategy — the file the coordinator must WAIT for.

  Mirrors `bench::transport::reduction_root_key` / `tree_proof_path` in the Rust
  code so the bash root-wait and the ROOT_PROOF_NAME plan var reference the SAME
  key the workers write:

    * reduction (default) -> `reduction_0_{padded-1}.proof`, where
      padded = padded_leaf_count(N). This is the single interval [0, padded-1]
      the gate's `on_interval_committed` treats as `RootReached`. e.g. N=500 ->
      reduction_0_511.proof, N=125 -> reduction_0_127.proof.
    * hex (explicit opt-out) -> `tree_L{depth}_N0.proof` (UNCHANGED).

  BUG B2: the coordinator previously hardcoded `tree_L{depth}_N0.proof`, which a
  reduction run NEVER produces -> the root-wait loop spun forever (the attempt-46
  GKE timeout). Choosing by strategy makes it wait for the real key.
  """
  if fold_strategy == "reduction":
    padded = padded_leaf_count(leaf_count)
    return f"reduction_0_{padded - 1}.proof"
  return f"tree_L{depth}_N0.proof"


def render_fungible(args, project_id, gsa_email, gcs_bucket, image_uri, leaf_chunk, leaf_cpu, leaf_mem, agg_cpu, agg_mem, gcs_relative_path, leaf_nodes=9, leaf_pods_per_node=14, agg_nodes=2, agg_pods_per_node=4):
  """Render the split fungible-pool Deployments + KEDA ScaledObjects.

  SPLIT topology (default): two fixed Deployments — `lighter-fungible-leaf`
  (subscribes prover-leaf-work-sub) + `lighter-fungible-agg` (subscribes
  prover-agg-work-sub) — statically partitioning the fleet. Two-thirds of the
  pool idles during whichever phase (leaf vs fold) is running; see render_unified
  for the self-balancing alternative.

  COST-OPT NOTE (#321): the agg request below (defaults ~26Gi from config.toml)
  is ~4x the MEASURED fold peak RSS of 6.00GB (attempt-48-hex; leaf peak was
  3.18GB). This is a separate over-provisioning worth right-sizing on the split
  path too, but is left as-is here to keep split behavior UNCHANGED (back-compat).
  """
  arch = args.arch if args.arch else "c3d"
  
  leaf_replicas = leaf_nodes * leaf_pods_per_node
  agg_replicas = agg_nodes * agg_pods_per_node

  
  ack_deadline = int(args.ack_deadline)
  grace = max(ack_deadline * 2, 120)

  deployment = f"""# Auto-generated by render_pod_spec.py --emit-fungible — do not edit by hand.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prover-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: {gsa_email or "GSA_EMAIL"}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighter-fungible-leaf
  labels:
    app: zkp-prover
    pool: fungible
    role: leaf-worker
    silicon-arch: {arch}
spec:
  strategy:
    type: Recreate
  replicas: {leaf_replicas}
  selector:
    matchLabels:
      app: zkp-prover
      pool: fungible
      role: leaf-worker
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
        controller.kubernetes.io/pod-deletion-cost: "0"
      labels:
        app: zkp-prover
        pool: fungible
        role: leaf-worker
        silicon-arch: {arch}
    spec:
      serviceAccountName: prover-sa
      terminationGracePeriodSeconds: {grace}
      nodeSelector:
        role: fungible-leaf
        silicon-arch: {arch}
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "zkp-prover"
        effect: "NoSchedule"
      - key: "cloud.google.com/gke-spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: prover
        image: {image_uri}
        command: ["prover-node", "work"]
        args:
        - "--transport=pubsub"
        - "--radix=$(RADIX)"
        - "--tx-per-proof=$(TX_PER_PROOF)"
        - "--fold-strategy=$(FOLD_STRATEGY)"
        - "--ack-deadline=$(ACK_DEADLINE)"
        env:
        - name: PROVER_PUBSUB_PROJECT
          value: "{project_id}"
        - name: PROVER_PUBSUB_TOPIC
          value: "{args.topic or "stark-proofs-topic"}"
        - name: PROVER_PUBSUB_SUBSCRIPTION
          value: "prover-leaf-work-sub"
        - name: PROVER_PUBSUB_EVENT_TOPIC
          value: "{args.event_topic or "prover-events-topic"}"
        - name: PROVER_PUBSUB_BUCKET
          value: "{gcs_bucket}"
        - name: PROVER_PUBSUB_OBJECT_PREFIX
          value: "{gcs_relative_path}/stark_proofs/"
        - name: ACK_DEADLINE
          value: "{ack_deadline}"
        - name: RADIX
          value: "{args.radix}"
        - name: TX_PER_PROOF
          value: "{leaf_chunk}"
        - name: FOLD_STRATEGY
          value: "{args.fold_strategy}"
        - name: RUST_LOG
          value: "info"
        - name: RUST_MIN_STACK
          value: "4294967296"
        - name: LIGHTER_PRESTATE_CORPUS
          value: "/data/captured_corpus.json"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 1"]
        resources:
          requests:
            cpu: "{leaf_cpu}"
            memory: "{leaf_mem}"
          limits:
            cpu: "{leaf_cpu}"
            memory: "{leaf_mem}"
        volumeMounts:
        - name: gcs-volume
          mountPath: /data/reports/stark_proofs
      volumes:
      - name: gcs-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: "{gcs_bucket}"
            mountOptions: "only-dir={gcs_relative_path}/stark_proofs,implicit-dirs"
            metadataCacheTTLSeconds: "0"
            metadataStatCacheCapacity: "0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighter-fungible-agg
  labels:
    app: zkp-prover
    pool: fungible
    role: aggregator
    silicon-arch: {arch}
spec:
  strategy:
    type: Recreate
  replicas: {agg_replicas}
  selector:
    matchLabels:
      app: zkp-prover
      pool: fungible
      role: aggregator
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
        controller.kubernetes.io/pod-deletion-cost: "0"
      labels:
        app: zkp-prover
        pool: fungible
        role: aggregator
        silicon-arch: {arch}
    spec:
      serviceAccountName: prover-sa
      terminationGracePeriodSeconds: {grace}
      nodeSelector:
        role: fungible-agg
        silicon-arch: {arch}
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "zkp-prover"
        effect: "NoSchedule"
      - key: "cloud.google.com/gke-spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: prover
        image: {image_uri}
        command: ["prover-node", "work"]
        args:
        - "--transport=pubsub"
        - "--radix=$(RADIX)"
        - "--tx-per-proof=$(TX_PER_PROOF)"
        - "--fold-strategy=$(FOLD_STRATEGY)"
        - "--ack-deadline=$(ACK_DEADLINE)"
        env:
        - name: PROVER_PUBSUB_PROJECT
          value: "{project_id}"
        - name: PROVER_PUBSUB_TOPIC
          value: "{args.topic or "stark-proofs-topic"}"
        - name: PROVER_PUBSUB_SUBSCRIPTION
          value: "prover-agg-work-sub"
        - name: PROVER_PUBSUB_EVENT_TOPIC
          value: "{args.event_topic or "prover-events-topic"}"
        - name: PROVER_PUBSUB_BUCKET
          value: "{gcs_bucket}"
        - name: PROVER_PUBSUB_OBJECT_PREFIX
          value: "{gcs_relative_path}/stark_proofs/"
        - name: ACK_DEADLINE
          value: "{ack_deadline}"
        - name: RADIX
          value: "{args.radix}"
        - name: TX_PER_PROOF
          value: "{leaf_chunk}"
        - name: FOLD_STRATEGY
          value: "{args.fold_strategy}"
        - name: RUST_LOG
          value: "info"
        - name: RUST_MIN_STACK
          value: "4294967296"
        - name: LIGHTER_PRESTATE_CORPUS
          value: "/data/captured_corpus.json"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 1"]
        resources:
          requests:
            cpu: "{agg_cpu}"
            memory: "{agg_mem}"
          limits:
            cpu: "{agg_cpu}"
            memory: "{agg_mem}"
        volumeMounts:
        - name: gcs-volume
          mountPath: /data/reports/stark_proofs
      volumes:
      - name: gcs-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: "{gcs_bucket}"
            mountOptions: "only-dir={gcs_relative_path}/stark_proofs,implicit-dirs"
            metadataCacheTTLSeconds: "0"
            metadataStatCacheCapacity: "0"
"""

  scaledobject = f"""# Auto-generated by render_pod_spec.py --emit-fungible — do not edit by hand.
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: lighter-fungible-leaf
  labels:
    app: zkp-prover
    pool: fungible
    role: leaf-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lighter-fungible-leaf
  minReplicaCount: 1
  maxReplicaCount: {leaf_replicas}
  cooldownPeriod: 300
  pollingInterval: 15
  triggers:
  - type: gcp-pubsub
    metadata:
      mode: SubscriptionSize
      subscriptionName: "prover-leaf-work-sub"
      value: "1"
      activationValue: "0"
      projectID: "{project_id}"
  advanced:
    restoreToOriginalReplicaCount: false
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Pods
            value: 1
            periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Pods
            value: 8
            periodSeconds: 30
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: lighter-fungible-agg
  labels:
    app: zkp-prover
    pool: fungible
    role: aggregator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lighter-fungible-agg
  minReplicaCount: 1
  maxReplicaCount: {agg_replicas}
  cooldownPeriod: 300
  pollingInterval: 15
  triggers:
  - type: gcp-pubsub
    metadata:
      mode: SubscriptionSize
      subscriptionName: "prover-agg-work-sub"
      value: "1"
      activationValue: "0"
      projectID: "{project_id}"
  advanced:
    restoreToOriginalReplicaCount: false
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Pods
            value: 1
            periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Pods
            value: 2
            periodSeconds: 30
"""

  dep_out = args.output.replace(".rendered.yaml", "-fungible.rendered.yaml")
  keda_out = args.output.replace(".rendered.yaml", "-fungible-keda.rendered.yaml")
  with open(dep_out, "w", encoding="utf-8") as f:
    f.write(deployment)
  with open(keda_out, "w", encoding="utf-8") as f:
    f.write(scaledobject)
  print(
      f"[OK] Rendered SPLIT FUNGIBLE-pool manifests to {dep_out} (Deployments: "
      f"leaf={leaf_replicas} replicas, agg={agg_replicas} replicas) and {keda_out} (KEDA ScaledObjects, "
      f"arch={arch}, radix={args.radix}, ack_deadline={ack_deadline}s, grace={grace}s)."
  )


def render_unified(args, project_id, gsa_email, gcs_bucket, image_uri, leaf_chunk, unified_cpu, unified_mem, gcs_relative_path, unified_replicas):
  """(#321) Render the UNIFIED fungible-pool Deployment + KEDA ScaledObject.

  ONE Deployment `lighter-fungible-prover`: every pod runs the SAME
  `prover-node work --transport=pubsub` binary and subscribes to the single
  no-filter subscription `prover-unified-work-sub`, so it pulls BOTH leaf and
  fold work and self-balances the leaf-vs-fold mix moment-to-moment. This is the
  opt-in alternative to the fixed split (leaf pods + agg pods) that idles
  two-thirds of the fleet per phase.

  Pod SIZING is FOLD-CAPABLE — a unified pod may pull a fold (the bigger job),
  so it must be sized for the larger of the two. Sizing basis is the MEASURED
  peak RSS measured on GKE: leaf ~3.13GB; fold 2.25GB with pre-baked node
  circuits (attempt-49, PR #338 — baking dropped fold RSS from the 6.00GB of the
  build-at-runtime attempt-48-hex). The default unified memory request is 4Gi —
  above BOTH the ~3.13GB leaf peak and the 2.25GB baked-fold peak (~1.3x margin
  over the larger, leaf) — a fold-capable pod that also proves leaves. NOT the
  split path's agg request of 26Gi, which is ~4x the measured 6.0GB fold peak
  (a separate over-provisioning; see the split-path comment). CPU/memory are
  overridable via --cpu / --memory. These numbers are measured, not fabricated.
  """
  arch = args.arch if args.arch else "c3d"

  ack_deadline = int(args.ack_deadline)
  grace = max(ack_deadline * 2, 120)

  deployment = f"""# Auto-generated by render_pod_spec.py --emit-fungible --pool-topology unified — do not edit by hand.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prover-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: {gsa_email or "GSA_EMAIL"}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighter-fungible-prover
  labels:
    app: zkp-prover
    pool: fungible
    role: unified-worker
    silicon-arch: {arch}
spec:
  strategy:
    type: Recreate
  replicas: {unified_replicas}
  selector:
    matchLabels:
      app: zkp-prover
      pool: fungible
      role: unified-worker
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
        controller.kubernetes.io/pod-deletion-cost: "0"
      labels:
        app: zkp-prover
        pool: fungible
        role: unified-worker
        silicon-arch: {arch}
    spec:
      serviceAccountName: prover-sa
      terminationGracePeriodSeconds: {grace}
      nodeSelector:
        role: fungible-leaf
        silicon-arch: {arch}
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "zkp-prover"
        effect: "NoSchedule"
      - key: "cloud.google.com/gke-spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: prover
        image: {image_uri}
        command: ["prover-node", "work"]
        args:
        - "--transport=pubsub"
        - "--radix=$(RADIX)"
        - "--tx-per-proof=$(TX_PER_PROOF)"
        - "--fold-strategy=$(FOLD_STRATEGY)"
        - "--ack-deadline=$(ACK_DEADLINE)"
        env:
        - name: PROVER_PUBSUB_PROJECT
          value: "{project_id}"
        - name: PROVER_PUBSUB_TOPIC
          value: "{args.topic or "stark-proofs-topic"}"
        # UNIFIED: single no-filter subscription — this pod pulls BOTH leaf and
        # fold work and self-balances. (Split uses prover-leaf/agg-work-sub.)
        - name: PROVER_PUBSUB_SUBSCRIPTION
          value: "prover-unified-work-sub"
        - name: PROVER_PUBSUB_EVENT_TOPIC
          value: "{args.event_topic or "prover-events-topic"}"
        - name: PROVER_PUBSUB_BUCKET
          value: "{gcs_bucket}"
        - name: PROVER_PUBSUB_OBJECT_PREFIX
          value: "{gcs_relative_path}/stark_proofs/"
        - name: ACK_DEADLINE
          value: "{ack_deadline}"
        - name: RADIX
          value: "{args.radix}"
        - name: TX_PER_PROOF
          value: "{leaf_chunk}"
        - name: FOLD_STRATEGY
          value: "{args.fold_strategy}"
        - name: RUST_LOG
          value: "info"
        - name: RUST_MIN_STACK
          value: "4294967296"
        - name: LIGHTER_PRESTATE_CORPUS
          value: "/data/captured_corpus.json"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 1"]
        resources:
          requests:
            cpu: "{unified_cpu}"
            memory: "{unified_mem}"
          limits:
            cpu: "{unified_cpu}"
            memory: "{unified_mem}"
        volumeMounts:
        - name: gcs-volume
          mountPath: /data/reports/stark_proofs
      volumes:
      - name: gcs-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: "{gcs_bucket}"
            mountOptions: "only-dir={gcs_relative_path}/stark_proofs,implicit-dirs"
            metadataCacheTTLSeconds: "0"
            metadataStatCacheCapacity: "0"
"""

  scaledobject = f"""# Auto-generated by render_pod_spec.py --emit-fungible --pool-topology unified — do not edit by hand.
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: lighter-fungible-prover
  labels:
    app: zkp-prover
    pool: fungible
    role: unified-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lighter-fungible-prover
  minReplicaCount: 1
  maxReplicaCount: {unified_replicas}
  cooldownPeriod: 300
  pollingInterval: 15
  triggers:
  - type: gcp-pubsub
    metadata:
      mode: SubscriptionSize
      subscriptionName: "prover-unified-work-sub"
      value: "1"
      activationValue: "0"
      projectID: "{project_id}"
  advanced:
    restoreToOriginalReplicaCount: false
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Pods
            value: 1
            periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Pods
            value: 8
            periodSeconds: 30
"""

  dep_out = args.output.replace(".rendered.yaml", "-fungible.rendered.yaml")
  keda_out = args.output.replace(".rendered.yaml", "-fungible-keda.rendered.yaml")
  with open(dep_out, "w", encoding="utf-8") as f:
    f.write(deployment)
  with open(keda_out, "w", encoding="utf-8") as f:
    f.write(scaledobject)
  print(
      f"[OK] Rendered UNIFIED FUNGIBLE-pool manifests to {dep_out} (Deployment: "
      f"lighter-fungible-prover={unified_replicas} replicas, sub=prover-unified-work-sub, "
      f"FOLD-CAPABLE mem={unified_mem} [measured RSS: leaf ~3.13GB / baked-fold 2.25GB, attempt-49 #338]) "
      f"and {keda_out} (KEDA ScaledObject on prover-unified-work-sub, arch={arch}, "
      f"radix={args.radix}, ack_deadline={ack_deadline}s, grace={grace}s)."
  )


def render_redis(args):
  redis_yaml = """# Auto-generated by render_pod_spec.py — do not edit by hand.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighter-redis
  labels:
    app: lighter-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lighter-redis
  template:
    metadata:
      labels:
        app: lighter-redis
    spec:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "zkp-prover"
        effect: "NoSchedule"
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: lighter-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
"""
  out_path = args.output.replace(".rendered.yaml", "-redis.rendered.yaml")
  with open(out_path, "w", encoding="utf-8") as f:
    f.write(redis_yaml)
  print(f"[OK] Rendered REDIS manifest to {out_path}")


def render_active_coordinator(args, project_id, image_uri):
  topic = args.topic or "PLACEHOLDER_TOPIC"
  event_subscription = args.event_subscription or "PLACEHOLDER_EVENT_SUBSCRIPTION"
  
  active_coordinator_yaml = f"""# Auto-generated by render_pod_spec.py — do not edit by hand.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighter-active-coordinator
  labels:
    app: lighter-active-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lighter-active-coordinator
  template:
    metadata:
      labels:
        app: lighter-active-coordinator
    spec:
      serviceAccountName: prover-sa
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "zkp-prover"
        effect: "NoSchedule"
      containers:
      - name: coordinator
        image: {image_uri}
        command: ["lighter-coordinator"]
        env:
        - name: PROVER_PUBSUB_PROJECT
          value: "{project_id}"
        - name: PROVER_EVENTS_SUBSCRIPTION
          value: "{event_subscription}"
        - name: PROVER_WORK_TOPIC
          value: "{topic}"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: RUST_LOG
          value: "info"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
"""
  out_path = args.output.replace(".rendered.yaml", "-active-coordinator.rendered.yaml")
  with open(out_path, "w", encoding="utf-8") as f:
    f.write(active_coordinator_yaml)
  print(f"[OK] Rendered ACTIVE COORDINATOR manifest to {out_path}")


def render_coordinator(args, project_id, gsa_email, gcs_bucket, image_uri, leaf_chunk, gcs_relative_path, leaf_count, depth):
  arch = args.arch if args.arch else "c3d"
  mount_opts = f"only-dir={gcs_relative_path},implicit-dirs"
  
  # (#321 Phase 9) The root proof file to wait for, chosen by fold strategy: the
  # reduction pipeline commits `reduction_0_{padded-1}.proof` (NOT the hex
  # `tree_L{depth}_N0.proof`), so a reduction run must wait for that exact key or
  # the loop spins forever (the attempt-46 GKE timeout, BUG B2).
  root_proof_basename = root_proof_name(args.fold_strategy, depth, leaf_count)
  root_proof_file = f"/data/reports/stark_proofs/{root_proof_basename}"
  
  coordinator_yaml = f"""apiVersion: batch/v1
kind: Job
metadata:
  name: lighter-coordinator
  labels:
    app: zkp-prover
    role: coordinator
    silicon-arch: {arch}
spec:
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        role: coordinator
        silicon-arch: {arch}
    spec:
      serviceAccountName: prover-sa
      nodeSelector:
        silicon-arch: {arch}
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "zkp-prover"
        effect: "NoSchedule"
      restartPolicy: OnFailure
      containers:
      - name: coordinator
        image: {image_uri}
        command: ["bash", "-c", "echo '[INFO] Waiting for root proof {root_proof_file}...'; while [ ! -f {root_proof_file} ]; do sleep 5; done; echo '[INFO] Root proof found, starting verification...'; prover-node root-coordinator --block-number 1042 --radix {args.radix} --leaf-count {leaf_count} --node-idx 0 --tx-per-proof {leaf_chunk} --fold-strategy {args.fold_strategy}"]
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: gcs-volume
          mountPath: /data/reports
      volumes:
      - name: gcs-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: "{gcs_bucket}"
            mountOptions: "{mount_opts}"
"""
  out_path = args.output.replace(".rendered.yaml", "-coordinator.rendered.yaml")
  with open(out_path, "w", encoding="utf-8") as f:
    f.write(coordinator_yaml)
  print(f"[OK] Rendered COORDINATOR manifest to {out_path}")


def render_seeder(args, project_id, gsa_email, gcs_bucket, image_uri, leaf_chunk, gcs_relative_path):
  topic = args.topic or "PLACEHOLDER_TOPIC"
  subscription = args.subscription or "PLACEHOLDER_SUBSCRIPTION"
  event_topic = args.event_topic or "PLACEHOLDER_EVENT_TOPIC"
  
  object_prefix = f"{gcs_relative_path}/stark_proofs/"
  mount_opts = f"only-dir={gcs_relative_path},implicit-dirs"
  
  seeder_yaml = f"""# Auto-generated by render_pod_spec.py --emit-fungible — do not edit by hand.
apiVersion: batch/v1
kind: Job
metadata:
  name: lighter-seeder
  labels:
    app: zkp-seeder
spec:
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        app: zkp-seeder
    spec:
      serviceAccountName: prover-sa
      restartPolicy: Never
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "zkp-prover"
        effect: "NoSchedule"
      containers:
      - name: seeder
        image: {image_uri}
        command: ["prover-node", "work"]
        args:
        - "--transport=pubsub"
        - "--seed"
        - "--blocks=$(BLOCKS)"
        - "--radix=$(RADIX)"
        - "--tx-per-proof=$(TX_PER_PROOF)"
        - "--fold-strategy=$(FOLD_STRATEGY)"
        - "--ack-deadline=$(ACK_DEADLINE)"
        env:
        - name: PROVER_PUBSUB_PROJECT
          value: "{project_id}"
        - name: PROVER_PUBSUB_TOPIC
          value: "{topic}"
        - name: PROVER_PUBSUB_SUBSCRIPTION
          value: "{subscription}"
        - name: PROVER_PUBSUB_EVENT_TOPIC
          value: "{event_topic}"
        - name: PROVER_PUBSUB_BUCKET
          value: "{gcs_bucket}"
        - name: PROVER_PUBSUB_OBJECT_PREFIX
          value: "{object_prefix}"
        - name: BLOCKS
          value: "{args.blocks}"
        - name: ACK_DEADLINE
          value: "{args.ack_deadline}"
        - name: RADIX
          value: "{args.radix}"
        - name: TX_PER_PROOF
          value: "{leaf_chunk}"
        - name: FOLD_STRATEGY
          value: "{args.fold_strategy}"
        - name: RUST_LOG
          value: "info"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        volumeMounts:
        - name: gcs-volume
          mountPath: /data/reports
      volumes:
      - name: gcs-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: "{gcs_bucket}"
            mountOptions: "{mount_opts}"
            metadataCacheTTLSeconds: "0"
            metadataStatCacheCapacity: "0"
"""
  out_path = args.output.replace(".rendered.yaml", "-seeder.rendered.yaml")
  with open(out_path, "w", encoding="utf-8") as f:
    f.write(seeder_yaml)
  print(f"[OK] Rendered SEEDER manifest to {out_path}")


def main():
  parser = argparse.ArgumentParser(description="Render dynamic K8s Proving Pod manifest")
  parser.add_argument("--config", default="config.toml", help="Path to config.toml")
  parser.add_argument("--arch", default="", help="Silicon architecture override (c4a, c3d, t2d, c4d)")
  parser.add_argument(
      "--blocks",
      type=int,
      default=2,
      help="K8s pipeline PARALLELISM (concurrent Job pods per level). NOTE: this "
           "is DISTINCT from the `prover-node work --blocks` 3-knob REPLAY count "
           "(issue #310): here it caps Indexed-Job parallelism, it does NOT replay "
           "the block. Left unchanged for back-compat.",
  )
  parser.add_argument("--input", default="infra-as-code/kubernetes/prover_pod_unit.yaml", help="Input YAML")
  parser.add_argument("--output", default="infra-as-code/kubernetes/prover_pod_unit.rendered.yaml", help="Output YAML")
  parser.add_argument("--image", required=True, help="Container release tag or 'default'")
  parser.add_argument(
      "--radix",
      type=int,
      default=16,
      help="Reduction tree radix (fan-in per node). Default 16 — the real "
           "workload radix (shallow trees at real N: 100→depth 2, 500→depth 3) "
           "matching the prover-node CLI default (issue #310). Pass --radix 2 for "
           "the tiny smoke / back-compat path; radix-2 stays fully supported.",
  )
  parser.add_argument(
      "--leaf-count",
      type=int,
      default=0,
      help="Total number of leaf proofs N (decoupled from radix). Defaults to "
           "radix for back-compat with the single-level (N == radix) pipeline.",
  )
  parser.add_argument("--benchmark-id", default="", help="Benchmark ID for GCS path isolation")
  parser.add_argument(
      "--chunk",
      type=int,
      default=0,
      help="Transactions per leaf chunk (C). When > 0, OVERRIDES the config.toml "
           "per-arch chunk_size — this is how the Cloud Build _CHUNK_SIZE / Makefile "
           "GKE_CHUNK reaches the rendered pods. 0 (default) = fall back to config.toml. "
           "Fixes the plumbing gap where _CHUNK_SIZE was echoed but never applied "
           "(attempt-47 requested C=4 but ran C=1).",
  )
  # ── Fungible-pool path (issue #302): emit the KEDA-autoscaled
  #    `prover-node work --transport=pubsub` Deployment + ScaledObject instead of
  #    the phase-locked per-level Indexed Jobs. This is the FUNGIBLE-AUTOSCALED
  #    orchestration; the default (no --emit-fungible) keeps emitting the
  #    phase-locked per-level Job path (#293/#297). Both are valid; see
  #    infra-as-code/kubernetes/README.md.
  parser.add_argument(
      "--emit-fungible",
      action="store_true",
      help="Emit the fungible-pool Deployment + KEDA ScaledObject (autoscaled "
           "prover-node work) instead of the phase-locked per-level Jobs.",
  )
  parser.add_argument("--topic", default="", help="(fungible) Pub/Sub topic id for follow-on fold descriptors")
  parser.add_argument("--subscription", default="", help="(fungible) Pub/Sub subscription id the pool pulls work from")
  parser.add_argument("--baseload", type=int, default=6, help="(fungible) baseload replicas (KEDA min; ~60%% of peak parallel width, always-on)")
  parser.add_argument("--burst", type=int, default=80, help="(fungible) burst replicas added on top of baseload (KEDA max = baseload + burst)")
  parser.add_argument("--ack-deadline", type=int, default=180, help="(fungible) Pub/Sub ack deadline seconds (~2xP99; radix-16 fold ~80s on c3d-highcpu-16, live 500-tx run; hardware-dependent, re-derive per instance type)")
  parser.add_argument("--cpu", default="", help="(fungible) CPU request override")
  parser.add_argument("--memory", default="", help="(fungible) Memory request override")
  parser.add_argument("--event-topic", default="", help="(fungible) Pub/Sub topic id for coordinator events")
  parser.add_argument("--event-subscription", default="", help="(fungible) Pub/Sub subscription id for coordinator events")
  # ── #321 Phase 8: reduction-tree fold strategy. `reduction` (default) is the
  #    order-free reducer that now runs on GKE; `hex` is the explicit opt-out
  #    legacy radix-16 fold. Threaded into the seeder + fungible leaf/agg `work`
  #    args as `--fold-strategy=<value>` so the rendered manifest is EXPLICIT
  #    about which strategy runs (the CLI default is also reduction, so the flag
  #    is belt-and-braces + the hex opt-out mechanism). The coordinator routes
  #    folds by each descriptor's fold_strategy — set by the reduction seeder —
  #    so it needs NO flag.
  parser.add_argument(
      "--fold-strategy",
      default="reduction",
      choices=["reduction", "hex"],
      help="(#321) Reduction-tree fold strategy for the seeder + fungible pool: "
           "'reduction' (default, order-free) or 'hex' (explicit opt-out, legacy "
           "radix-16 fold). Threaded into the seeder/leaf/agg 'work' args.",
  )
  # ── #321 Unified pool topology (SELECTABLE, opt-in) ─────────────────────────
  # 'split' (DEFAULT, zero behavior change): emit the two fixed Deployments —
  #   `lighter-fungible-leaf` (subscribes prover-leaf-work-sub) and
  #   `lighter-fungible-agg` (subscribes prover-agg-work-sub) — plus their two
  #   KEDA ScaledObjects. The fleet is statically partitioned; two-thirds of the
  #   pool idles during whichever phase (leaf vs fold) is running.
  # 'unified' (opt-in): emit ONE Deployment `lighter-fungible-prover` where EVERY
  #   pod pulls BOTH leaf and fold work from the single no-filter subscription
  #   `prover-unified-work-sub` and self-balances the leaf-vs-fold mix. The same
  #   `prover-node work --transport=pubsub` binary handles any role it pulls, so
  #   the ONLY difference from split is which subscription the pod subscribes to.
  #   Sized FOLD-CAPABLE (the bigger job) — see render_unified for the measured
  #   attempt-48 RSS basis. Both paths stay valid so we can A/B them.
  parser.add_argument(
      "--pool-topology",
      default="split",
      choices=["split", "unified"],
      help="(#321) Fungible worker-pool topology: 'split' (default) emits the two "
           "fixed leaf/agg Deployments (prover-leaf-work-sub + prover-agg-work-sub); "
           "'unified' emits ONE self-balancing Deployment where every pod pulls "
           "both leaf and fold work from prover-unified-work-sub. Split preserves "
           "current behavior; unified is opt-in.",
  )
  parser.add_argument(
      "--pool-replicas",
      type=int,
      default=0,
      help="(#321) UNIFIED pool replica count. 0 (default) derives a sensible "
           "total = leaf_replicas (one pool now does everything the split leaf "
           "pool used to, and drains folds too). Ignored under --pool-topology=split.",
  )
  args = parser.parse_args()

  if not args.image or args.image.strip() == "":
    sys.exit("ERROR: --image argument is required for Kubernetes deployment manifest rendering.")
  image_tag = args.image.strip()
  if image_tag == "default":
    image_tag = "0.0.3-distributed-proving"

  if not os.path.exists(args.config):
    print(f"Error: Config file {args.config} not found.", file=sys.stderr)
    sys.exit(1)

  try:
    with open(args.config, "rb") as f:
      data = tomllib.load(f)
  except (TypeError, AttributeError):
    with open(args.config, "r", encoding="utf-8") as f:
      data = tomllib.load(f)

  gcs_bucket = data.get("gcp", {}).get("bench", {}).get("bucket", "kunal-scratch-tfstate")
  gsa_email = data.get("gcp", {}).get("target", {}).get("runtime_sa", {}).get("email", "")
  if not gsa_email:
    gsa_email = data.get("gcp", {}).get("target", {}).get("build_sa", {}).get("email", "")

  # Dynamically resolve registry URI from config.toml
  project_id = data.get("gcp", {}).get("defaults", {}).get("project", "kunal-scratch")
  registry_cfg = data.get("gcp", {}).get("registry", {})
  registry_region = registry_cfg.get("region", "us")
  registry_repo = registry_cfg.get("repository", "lighter-prover-iac")
  image_uri = f"{registry_region}-docker.pkg.dev/{project_id}/{registry_repo}/zkp-prover:{image_tag}"

  # ── Fungible-pool path (issue #302) ────────────────────────────────────────
  # When --emit-fungible is set, render the autoscaled Deployment + KEDA
  # ScaledObject and exit, instead of the phase-locked per-level Jobs below.
  if args.emit_fungible:
    # Derive leaf_chunk (transactions per chunk) from config.toml
    pod_cfg = data.get("proving_pod", {})
    defaults = pod_cfg.get("defaults", {})
    arch = args.arch if args.arch else str(defaults.get("arch", "c3d"))
    arch_cfg = pod_cfg.get(arch, {})
    
    leaf_cfg = arch_cfg.get("leaf_worker", {}) if arch_cfg else {}
    # --chunk (>0) OVERRIDES the config.toml chunk_size so the Cloud Build
    # _CHUNK_SIZE / Makefile GKE_CHUNK actually reaches the pods. Without this,
    # _CHUNK_SIZE was only echoed for logging and leaf_chunk silently fell back
    # to the config.toml default (1 for c3d) — attempt-47 asked for C=4 but ran C=1.
    config_chunk = int(leaf_cfg.get("chunk_size", 1 if arch in ("c3d", "c4d") else 4)) if leaf_cfg else (1 if arch in ("c3d", "c4d") else 4)
    leaf_chunk = args.chunk if getattr(args, "chunk", 0) and args.chunk > 0 else config_chunk
    
    # Extract cpu and memory requests from config.toml
    leaf_cpu = str(leaf_cfg.get("cpu_requests", "14")) if leaf_cfg else "14"
    leaf_mem = str(leaf_cfg.get("memory_requests", "27Gi")) if leaf_cfg else "27Gi"

    agg_cfg = arch_cfg.get("aggregator", {}) if arch_cfg else {}
    agg_cpu = str(agg_cfg.get("cpu_requests", "58")) if agg_cfg else "58"
    agg_mem = str(agg_cfg.get("memory_requests", "110Gi")) if agg_cfg else "110Gi"

    # We assume 500 transactions for the benchmark block (block 1042)
    txs_per_block = 500
    leaf_count = txs_per_block // leaf_chunk
    depth = max(tree_depth(leaf_count, args.radix), 1)

    benchmark_id = args.benchmark_id if args.benchmark_id else "none"
    gcs_relative_path = f"benchmark-reports/{benchmark_id}/{image_tag}/{arch}"

    leaf_nodes = int(leaf_cfg.get("node_count", 9)) if leaf_cfg else 9
    leaf_pods_per_node = int(leaf_cfg.get("pods_per_node", 14)) if leaf_cfg else 14
    agg_nodes = int(agg_cfg.get("node_count", 2)) if agg_cfg else 2
    agg_pods_per_node = int(agg_cfg.get("pods_per_node", 4)) if agg_cfg else 4
    leaf_replicas = leaf_nodes * leaf_pods_per_node

    render_redis(args)
    # ── #321 SELECTABLE pool topology ─────────────────────────────────────────
    # split (default): the two fixed leaf/agg Deployments (unchanged).
    # unified (opt-in): ONE self-balancing `lighter-fungible-prover` Deployment.
    if getattr(args, "pool_topology", "split") == "unified":
      # UNIFIED sizing is FOLD-CAPABLE (the bigger job). Basis = MEASURED peak RSS
      # from attempt-48-hex on GKE: leaf 3.18GB, fold 6.00GB. Default memory
      # request 8Gi = fold 6.00GB x ~1.3 headroom (NOT the split agg 26Gi guess,
      # which is ~4x the measured 6.0GB). Overridable via --cpu / --memory.
      unified_cpu = args.cpu if getattr(args, "cpu", "") else leaf_cpu
      unified_mem = args.memory if getattr(args, "memory", "") else "4Gi"
      # Replicas: --pool-replicas if given (>0), else a sensible total = the
      # split leaf pool width (one pool now does everything: leaves AND folds).
      unified_replicas = args.pool_replicas if getattr(args, "pool_replicas", 0) and args.pool_replicas > 0 else leaf_replicas
      render_unified(args, project_id, gsa_email, gcs_bucket, image_uri, leaf_chunk, unified_cpu, unified_mem, gcs_relative_path, unified_replicas)
    else:
      render_fungible(args, project_id, gsa_email, gcs_bucket, image_uri, leaf_chunk, leaf_cpu, leaf_mem, agg_cpu, agg_mem, gcs_relative_path, leaf_nodes, leaf_pods_per_node, agg_nodes, agg_pods_per_node)
    render_active_coordinator(args, project_id, image_uri)
    render_coordinator(args, project_id, gsa_email, gcs_bucket, image_uri, leaf_chunk, gcs_relative_path, leaf_count, depth)
    render_seeder(args, project_id, gsa_email, gcs_bucket, image_uri, leaf_chunk, gcs_relative_path)
    return

  pod_cfg = data.get("proving_pod", {})
  defaults = pod_cfg.get("defaults", {})
  
  arch = args.arch if args.arch else str(defaults.get("arch", "c3d"))
  arch_cfg = pod_cfg.get(arch, {})
  if not arch_cfg:
    print(f"Warning: No [proving_pod.{arch}] found in {args.config}, using fallbacks.", file=sys.stderr)
    arch_cfg = {}

  leaf_cfg = arch_cfg.get("leaf_worker", {})
  agg_cfg = arch_cfg.get("aggregator", {})

  kube_arch = "arm64" if arch == "c4a" else "amd64"

  leaf_cpu = str(leaf_cfg.get("cpu_requests", "30" if arch in ("c3d", "t2d", "c4d") else "64"))
  leaf_mem = str(leaf_cfg.get("memory_requests", "60Gi" if arch in ("c3d", "c4d") else "128Gi"))
  leaf_chunk = int(leaf_cfg.get("chunk_size", 1 if arch in ("c3d", "c4d") else 4))
  
  # Leaf count N is DECOUPLED from radix (fan-in). For back-compat, when
  # --leaf-count is omitted (0) it defaults to radix (the old single-level
  # N == radix pipeline). For an Indexed leaf Job, completions == N: we prove one
  # leaf per completion index. Parallelism is capped by BLOCKS and by N.
  leaf_count = args.leaf_count if args.leaf_count and args.leaf_count > 0 else args.radix
  if leaf_count < 1:
    sys.exit("ERROR: --leaf-count (or --radix fallback) must be >= 1.")

  completions = leaf_count
  parallelism = min(args.blocks, completions)

  # Dynamic tree geometry: depth = ceil(log_radix(N)); each level L has
  # ceil(N / radix^L) tree-node Jobs. depth == 0 (N == 1) means a lone leaf with
  # no folding — still emit one trivial level-1 Job for a uniform pipeline.
  depth = max(tree_depth(leaf_count, args.radix), 1)

  agg_cpu = str(agg_cfg.get("cpu_requests", "30" if arch in ("c3d", "c4d") else "16"))
  agg_mem = str(agg_cfg.get("memory_requests", "60Gi" if arch in ("c3d", "c4d") else "32Gi"))
  agg_replicas = 1 * args.blocks

  if not os.path.exists(args.input):
    print(f"Error: Input YAML {args.input} not found.", file=sys.stderr)
    sys.exit(1)

  mount_opts = "implicit-dirs"
  if args.benchmark_id:
    # GCS Fuse only-dir option mounts a subdirectory as the root of the volume
    mount_opts += f",only-dir={args.benchmark_id}"

  # Split rendering into Leaf and Tree Jobs
  leaf_rendered = f"""apiVersion: v1
kind: ServiceAccount
metadata:
  name: prover-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: {gsa_email}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: lighter-leaf-worker
  labels:
    app: zkp-prover
    role: leaf-worker
    silicon-arch: {arch}
spec:
  parallelism: {parallelism}
  completions: {completions}
  completionMode: Indexed
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        role: leaf-worker
        silicon-arch: {arch}
    spec:
      serviceAccountName: prover-sa
      nodeSelector:
        role: leaf-worker
        silicon-arch: {arch}
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "zkp-prover"
        effect: "NoSchedule"
      restartPolicy: OnFailure
      containers:
      - name: prover
        image: {image_uri}
        command: ["sh", "-c", "prover-node leaf-worker --chunk-idx $JOB_COMPLETION_INDEX --tx-per-proof {leaf_chunk}"]
        resources:
          limits:
            cpu: "{leaf_cpu}"
            memory: "{leaf_mem}"
          requests:
            cpu: "{leaf_cpu}"
            memory: "{leaf_mem}"
        volumeMounts:
        - name: gcs-volume
          mountPath: /data/reports
      volumes:
      - name: gcs-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: "{gcs_bucket}"
            mountOptions: "{mount_opts}"
"""

  # One Indexed tree-node Job PER LEVEL (1..=depth). At level L the Job runs
  # `nodes_at_level(N, radix, L)` completions, each folding up to `radix` children
  # read from the transport ($JOB_COMPLETION_INDEX -> --node-idx). The level-L
  # binary now derives node geometry from --leaf-count, so the same image folds
  # any level. The final (root) level always has exactly one completion.
  #
  # GKE cross-level ordering (#295, follow-up to #291/#293): Kubernetes batch/v1
  # Jobs have no native inter-Job completion gating, so level L+1 must NOT start
  # before every level-L node proof exists in the shared transport. We resolve
  # this with Cloud Build *sequential gating*: each level is emitted to its own
  # uniquely-named manifest (`...-tree-l{level}.rendered.yaml`, Job
  # `lighter-tree-aggregator-l{level}`) and the orchestrator
  # (`infra-as-code/cloudbuild-distributed.yaml`, ENGINE=gke) applies them one at
  # a time, blocking on `kubectl wait --for=condition=complete` between levels.
  # To keep depth/node-counts a SINGLE source of truth (no second computation in
  # bash), this renderer also writes a machine-readable plan file
  # (`...-tree.plan.env`) the orchestrator sources to drive its loop. The binary
  # already fails fast when a child proof is missing; the `kubectl wait` is the
  # actual gate that enforces ordering on a real cluster.
  level_jobs = []          # combined doc for back-compat / inspection
  level_manifests = {}     # level -> rendered single-Job YAML (per-level files)
  level_node_counts = {}   # level -> nodes_at_level (single source of truth)
  for level in range(1, depth + 1):
    level_nodes = nodes_at_level(leaf_count, args.radix, level)
    level_node_counts[level] = level_nodes
    is_root = (level == depth)
    level_parallelism = min(args.blocks, level_nodes)
    level_yaml = f"""apiVersion: batch/v1
kind: Job
metadata:
  name: lighter-tree-aggregator-l{level}
  labels:
    app: zkp-prover
    role: tree-node
    tree-level: "{level}"
    is-root-level: "{str(is_root).lower()}"
    silicon-arch: {arch}
spec:
  parallelism: {level_parallelism}
  completions: {level_nodes}
  completionMode: Indexed
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        role: tree-node
        tree-level: "{level}"
        silicon-arch: {arch}
    spec:
      serviceAccountName: prover-sa
      nodeSelector:
        role: tree-node
        silicon-arch: {arch}
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "zkp-prover"
        effect: "NoSchedule"
      restartPolicy: OnFailure
      containers:
      - name: aggregator
        image: {image_uri}
        command: ["sh", "-c", "prover-node tree-node --level {level} --node-idx $JOB_COMPLETION_INDEX --radix {args.radix} --leaf-count {leaf_count} --tx-per-proof {leaf_chunk}"]
        resources:
          limits:
            cpu: "{agg_cpu}"
            memory: "{agg_mem}"
          requests:
            cpu: "{agg_cpu}"
            memory: "{agg_mem}"
        volumeMounts:
        - name: gcs-volume
          mountPath: /data/reports
      volumes:
      - name: gcs-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: "{gcs_bucket}"
            mountOptions: "{mount_opts}"
"""
    level_manifests[level] = level_yaml
    level_jobs.append(level_yaml)

  # RootCoordinator Job: harvests + verifies the single root proof at the
  # dynamically-computed root level (the binary derives root_level from
  # --leaf-count, so no level is hardcoded here either).
  root_job = f"""apiVersion: batch/v1
kind: Job
metadata:
  name: lighter-root-coordinator
  labels:
    app: zkp-prover
    role: root-coordinator
    silicon-arch: {arch}
spec:
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        role: root-coordinator
        silicon-arch: {arch}
    spec:
      serviceAccountName: prover-sa
      nodeSelector:
        role: tree-node
        silicon-arch: {arch}
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "zkp-prover"
        effect: "NoSchedule"
      restartPolicy: OnFailure
      containers:
      - name: coordinator
        image: {image_uri}
        command: ["prover-node", "root-coordinator", "--radix", "{args.radix}", "--leaf-count", "{leaf_count}", "--node-idx", "0", "--tx-per-proof", "{leaf_chunk}"]
        resources:
          limits:
            cpu: "{agg_cpu}"
            memory: "{agg_mem}"
          requests:
            cpu: "{agg_cpu}"
            memory: "{agg_mem}"
        volumeMounts:
        - name: gcs-volume
          mountPath: /data/reports
      volumes:
      - name: gcs-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: "{gcs_bucket}"
            mountOptions: "{mount_opts}"
"""

  tree_rendered = "---\n".join(level_jobs) + "---\n" + root_job

  leaf_output = args.output.replace(".rendered.yaml", "-leaf.rendered.yaml")
  tree_output = args.output.replace(".rendered.yaml", "-tree.rendered.yaml")
  root_output = args.output.replace(".rendered.yaml", "-tree-root.rendered.yaml")
  plan_output = args.output.replace(".rendered.yaml", "-tree.plan.env")

  with open(leaf_output, "w", encoding="utf-8") as f:
    f.write(leaf_rendered)
  # Combined tree doc retained for back-compat / human inspection.
  with open(tree_output, "w", encoding="utf-8") as f:
    f.write(tree_rendered)
  # Root coordinator as its own manifest so the orchestrator applies/waits on it
  # after the last tree level completes.
  with open(root_output, "w", encoding="utf-8") as f:
    f.write(root_job)

  # Per-level tree-node manifests with deterministic, loop-targetable names so
  # Cloud Build can apply + `kubectl wait` each level IN ORDER (cross-level gate).
  per_level_outputs = []
  for level in range(1, depth + 1):
    level_output = args.output.replace(".rendered.yaml", f"-tree-l{level}.rendered.yaml")
    with open(level_output, "w", encoding="utf-8") as f:
      f.write(level_manifests[level])
    per_level_outputs.append(level_output)

  # Machine-readable plan file: the SINGLE source of truth for depth/node-counts
  # that the cloudbuild ENGINE=gke loop sources (no second computation in bash).
  # ROOT_LEVEL == depth (hex per-level topology); the root proof NAME depends on
  # the fold strategy — (#321 Phase 9) reduction commits
  # `reduction_0_{padded-1}.proof`, hex commits `tree_L{ROOT_LEVEL}_N0.proof`
  # (BUG B2: waiting on the wrong name never completes).
  root_level = depth
  root_proof_basename = root_proof_name(args.fold_strategy, depth, leaf_count)
  plan_lines = [
      "# Auto-generated by render_pod_spec.py — do not edit by hand.",
      "# Sourced by infra-as-code/cloudbuild-distributed.yaml (ENGINE=gke) to drive",
      "# the cross-level Job gating loop. Single source of truth for tree geometry.",
      f"TREE_DEPTH={depth}",
      f"ROOT_LEVEL={root_level}",
      f'TREE_LEVELS="{" ".join(str(l) for l in range(1, depth + 1))}"',
      f"LEAF_COUNT={leaf_count}",
      f"RADIX={args.radix}",
      f"FOLD_STRATEGY={args.fold_strategy}",
      f"ROOT_PROOF_NAME={root_proof_basename}",
  ]
  for level in range(1, depth + 1):
    plan_lines.append(f"TREE_LEVEL_{level}_NODES={level_node_counts[level]}")
  with open(plan_output, "w", encoding="utf-8") as f:
    f.write("\n".join(plan_lines) + "\n")

  print(
      f"[OK] Dynamically rendered K8s Proving Pod Jobs to {leaf_output}, "
      f"{tree_output}, per-level [{', '.join(per_level_outputs)}], {root_output}, "
      f"and plan {plan_output} (arch={arch}, blocks={args.blocks}, "
      f"radix={args.radix}, leaf_count={leaf_count}, depth={depth}, "
      f"root_level={root_level}, leaf_chunk={leaf_chunk})"
  )


if __name__ == "__main__":
  main()
