#!/usr/bin/env python3
"""Renders prover_pod_unit.rendered.yaml dynamically from config.toml proving_pod profiles."""

import argparse
import os
import sys

try:
  import tomllib  # Python 3.11+
except ImportError:
  try:
    import tomli as tomllib
  except ImportError:
    import toml as tomllib


def tree_depth(n, radix):
  """ceil(log_radix(n)): number of node levels above N leaves.

  Mirrors `tree_depth` in bench/src/bin/prover_node.rs. Computed iteratively to
  avoid float rounding hazards near exact powers (e.g. log2(8) == 3 exactly).
  """
  if radix < 2:
    raise ValueError("radix must be >= 2")
  if n <= 1:
    return 0
  depth = 0
  span = 1  # radix**depth
  while span < n:
    span *= radix
    depth += 1
  return depth


def nodes_at_level(n, radix, level):
  """ceil(n / radix**level): node count at a 1-indexed tree level.

  Mirrors `nodes_at_level` in bench/src/bin/prover_node.rs. The root level always
  has exactly one node.
  """
  if level < 1:
    raise ValueError("tree levels are 1-indexed")
  divisor = radix ** level
  return max((n + divisor - 1) // divisor, 1)


def render_fungible(args, project_id, gsa_email, gcs_bucket, image_uri, leaf_chunk, default_cpu, default_mem):
  """Render the fungible-pool Deployment + KEDA ScaledObject (issue #302).

  This is the FUNGIBLE-AUTOSCALED path: one pod shape running
  `prover-node work --transport=pubsub`, scaled by KEDA on Pub/Sub backlog
  (baseload + burst, never scale-to-zero). It is distinct from the phase-locked
  per-level Indexed-Job path (#293/#297) emitted by the rest of this script.
  See infra-as-code/kubernetes/README.md for the comparison and ADR §4/§7.

  All cluster-applying actions are out of scope here; this only writes manifests.
  Live behavior (KEDA install, real backlog scaling, GKE scheduling) is
  TODO(confirm-on-live-run).
  """
  baseload = max(int(args.baseload), 1)  # never 0 — baseload is always-on (ADR §7)
  burst = max(int(args.burst), 0)
  max_replicas = baseload + burst
  arch = args.arch if args.arch else "c3d"
  # Use CLI override if present, else use default from config.toml
  cpu = args.cpu if args.cpu else default_cpu
  mem = args.memory if args.memory else default_mem
  topic = args.topic or "PLACEHOLDER_TOPIC"
  subscription = args.subscription or "PLACEHOLDER_SUBSCRIPTION"
  event_topic = args.event_topic or "PLACEHOLDER_EVENT_TOPIC"
  ack_deadline = int(args.ack_deadline)
  # terminationGracePeriod >= max prove time on target instance; sized for the
  # live 500-tx run's ≈80s radix-16 folds on c3d-highcpu-16 with comfortable
  # headroom (default ack_deadline 180s ⇒ grace 360s).
  grace = max(ack_deadline * 2, 120)

  deployment = f"""# Auto-generated by render_pod_spec.py --emit-fungible — do not edit by hand.
# Fungible-pool Deployment: autoscaled `prover-node work --transport=pubsub`.
# See infra-as-code/kubernetes/fungible_pool.yaml for the annotated template and
# docs/decisions/ADR-distributed-recursive-proving-architecture.md (§4, §7).
# TODO(confirm-on-live-run): live KEDA/GKE rollout + end-to-end proving.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prover-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: {gsa_email or "GSA_EMAIL"}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighter-fungible-prover
  labels:
    app: zkp-prover
    pool: fungible
    silicon-arch: {arch}
spec:
  replicas: {baseload}
  selector:
    matchLabels:
      app: zkp-prover
      pool: fungible
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
        controller.kubernetes.io/pod-deletion-cost: "0"
      labels:
        app: zkp-prover
        pool: fungible
        role: fungible-worker
        silicon-arch: {arch}
    spec:
      serviceAccountName: prover-sa
      terminationGracePeriodSeconds: {grace}
      nodeSelector:
        role: fungible-worker
        silicon-arch: {arch}
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "zkp-prover"
        effect: "NoSchedule"
      - key: "cloud.google.com/gke-spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: prover
        image: {image_uri}
        command: ["prover-node", "work"]
        args:
        - "--transport=pubsub"
        - "--radix=$(RADIX)"
        - "--tx-per-proof=$(TX_PER_PROOF)"
        - "--ack-deadline=$(ACK_DEADLINE)"
        env:
        - name: PROVER_PUBSUB_PROJECT
          value: "{project_id}"
        - name: PROVER_PUBSUB_TOPIC
          value: "{topic}"
        - name: PROVER_PUBSUB_SUBSCRIPTION
          value: "{subscription}"
        - name: PROVER_PUBSUB_EVENT_TOPIC
          value: "{event_topic}"
        - name: PROVER_PUBSUB_BUCKET
          value: "{gcs_bucket}"
        - name: PROVER_PUBSUB_OBJECT_PREFIX
          value: ""
        - name: ACK_DEADLINE
          value: "{ack_deadline}"
        - name: RADIX
          value: "{args.radix}"
        - name: TX_PER_PROOF
          value: "{leaf_chunk}"
        - name: RUST_LOG
          value: "info"
        - name: RUST_MIN_STACK
          value: "4294967296"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 1"]
        resources:
          requests:
            cpu: "{cpu}"
            memory: "{mem}"
          limits:
            cpu: "{cpu}"
            memory: "{mem}"
        volumeMounts:
        - name: gcs-volume
          mountPath: /data/reports/stark_proofs
      volumes:
      - name: gcs-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: "{gcs_bucket}"
            mountOptions: "implicit-dirs"
            metadataCacheTTLSeconds: "0"
            metadataStatCacheCapacity: "0"
"""

  scaledobject = f"""# Auto-generated by render_pod_spec.py --emit-fungible — do not edit by hand.
# KEDA ScaledObject: backlog autoscaling for the fungible pool. KEDA must be
# installed as a prerequisite (helm install keda kedacore/keda ...). NOT installed
# here. TODO(confirm-on-live-run): real backlog-driven scale up/down.
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: lighter-fungible-prover
  labels:
    app: zkp-prover
    pool: fungible
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lighter-fungible-prover
  minReplicaCount: {baseload}
  maxReplicaCount: {max_replicas}
  cooldownPeriod: 300
  pollingInterval: 15
  triggers:
  - type: gcp-pubsub
    metadata:
      mode: SubscriptionSize
      subscriptionName: "{subscription}"
      value: "1"
      activationValue: "0"
      projectID: "{project_id}"
  advanced:
    restoreToOriginalReplicaCount: false
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Pods
            value: 1
            periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Pods
            value: 8
            periodSeconds: 30
"""

  dep_out = args.output.replace(".rendered.yaml", "-fungible.rendered.yaml")
  keda_out = args.output.replace(".rendered.yaml", "-fungible-keda.rendered.yaml")
  with open(dep_out, "w", encoding="utf-8") as f:
    f.write(deployment)
  with open(keda_out, "w", encoding="utf-8") as f:
    f.write(scaledobject)
  print(
      f"[OK] Rendered FUNGIBLE-pool manifests to {dep_out} (Deployment, "
      f"baseload={baseload} replicas) and {keda_out} (KEDA ScaledObject, "
      f"min={baseload}, max={max_replicas}, arch={arch}, radix={args.radix}, "
      f"ack_deadline={ack_deadline}s, grace={grace}s). "
      f"Live KEDA/GKE rollout is TODO(confirm-on-live-run)."
  )


def render_redis(args):
  redis_yaml = """# Auto-generated by render_pod_spec.py — do not edit by hand.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighter-redis
  labels:
    app: lighter-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lighter-redis
  template:
    metadata:
      labels:
        app: lighter-redis
    spec:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "zkp-prover"
        effect: "NoSchedule"
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: lighter-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
"""
  out_path = args.output.replace(".rendered.yaml", "-redis.rendered.yaml")
  with open(out_path, "w", encoding="utf-8") as f:
    f.write(redis_yaml)
  print(f"[OK] Rendered REDIS manifest to {out_path}")


def render_coordinator(args, project_id, gsa_email, gcs_bucket, image_uri, leaf_chunk, gcs_relative_path, leaf_count, depth):
  arch = args.arch if args.arch else "c3d"
  mount_opts = f"only-dir={gcs_relative_path},implicit-dirs"
  
  # The root proof file we need to wait for
  root_proof_file = f"/data/reports/stark_proofs/tree_L{depth}_N0.proof"
  
  coordinator_yaml = f"""apiVersion: batch/v1
kind: Job
metadata:
  name: lighter-coordinator
  labels:
    app: zkp-prover
    role: coordinator
    silicon-arch: {arch}
spec:
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        role: coordinator
        silicon-arch: {arch}
    spec:
      serviceAccountName: prover-sa
      nodeSelector:
        silicon-arch: {arch}
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "zkp-prover"
        effect: "NoSchedule"
      restartPolicy: OnFailure
      containers:
      - name: coordinator
        image: {image_uri}
        command: ["bash", "-c", "echo '[INFO] Waiting for root proof {root_proof_file}...'; while [ ! -f {root_proof_file} ]; do sleep 5; done; echo '[INFO] Root proof found, starting verification...'; prover-node root-coordinator --block-number 1042 --radix {args.radix} --leaf-count {leaf_count} --node-idx 0 --tx-per-proof {leaf_chunk}"]
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: gcs-volume
          mountPath: /data/reports
      volumes:
      - name: gcs-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: "{gcs_bucket}"
            mountOptions: "{mount_opts}"
"""
  out_path = args.output.replace(".rendered.yaml", "-coordinator.rendered.yaml")
  with open(out_path, "w", encoding="utf-8") as f:
    f.write(coordinator_yaml)
  print(f"[OK] Rendered COORDINATOR manifest to {out_path}")


def render_seeder(args, project_id, gsa_email, gcs_bucket, image_uri, leaf_chunk, gcs_relative_path):
  topic = args.topic or "PLACEHOLDER_TOPIC"
  subscription = args.subscription or "PLACEHOLDER_SUBSCRIPTION"
  event_topic = args.event_topic or "PLACEHOLDER_EVENT_TOPIC"
  
  object_prefix = f"{gcs_relative_path}/stark_proofs/"
  mount_opts = f"only-dir={gcs_relative_path},implicit-dirs"
  
  seeder_yaml = f"""# Auto-generated by render_pod_spec.py --emit-fungible — do not edit by hand.
apiVersion: batch/v1
kind: Job
metadata:
  name: lighter-seeder
  labels:
    app: zkp-seeder
spec:
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        app: zkp-seeder
    spec:
      serviceAccountName: prover-sa
      restartPolicy: Never
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "zkp-prover"
        effect: "NoSchedule"
      containers:
      - name: seeder
        image: {image_uri}
        command: ["prover-node", "work"]
        args:
        - "--transport=pubsub"
        - "--seed"
        - "--radix=$(RADIX)"
        - "--tx-per-proof=$(TX_PER_PROOF)"
        - "--ack-deadline=$(ACK_DEADLINE)"
        env:
        - name: PROVER_PUBSUB_PROJECT
          value: "{project_id}"
        - name: PROVER_PUBSUB_TOPIC
          value: "{topic}"
        - name: PROVER_PUBSUB_SUBSCRIPTION
          value: "{subscription}"
        - name: PROVER_PUBSUB_EVENT_TOPIC
          value: "{event_topic}"
        - name: PROVER_PUBSUB_BUCKET
          value: "{gcs_bucket}"
        - name: PROVER_PUBSUB_OBJECT_PREFIX
          value: "{object_prefix}"
        - name: ACK_DEADLINE
          value: "{args.ack_deadline}"
        - name: RADIX
          value: "{args.radix}"
        - name: TX_PER_PROOF
          value: "{leaf_chunk}"
        - name: RUST_LOG
          value: "info"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        volumeMounts:
        - name: gcs-volume
          mountPath: /data/reports
      volumes:
      - name: gcs-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: "{gcs_bucket}"
            mountOptions: "{mount_opts}"
            metadataCacheTTLSeconds: "0"
            metadataStatCacheCapacity: "0"
"""
  out_path = args.output.replace(".rendered.yaml", "-seeder.rendered.yaml")
  with open(out_path, "w", encoding="utf-8") as f:
    f.write(seeder_yaml)
  print(f"[OK] Rendered SEEDER manifest to {out_path}")


def main():
  parser = argparse.ArgumentParser(description="Render dynamic K8s Proving Pod manifest")
  parser.add_argument("--config", default="config.toml", help="Path to config.toml")
  parser.add_argument("--arch", default="", help="Silicon architecture override (c4a, c3d, t2d, c4d)")
  parser.add_argument(
      "--blocks",
      type=int,
      default=2,
      help="K8s pipeline PARALLELISM (concurrent Job pods per level). NOTE: this "
           "is DISTINCT from the `prover-node work --blocks` 3-knob REPLAY count "
           "(issue #310): here it caps Indexed-Job parallelism, it does NOT replay "
           "the block. Left unchanged for back-compat.",
  )
  parser.add_argument("--input", default="infra-as-code/kubernetes/prover_pod_unit.yaml", help="Input YAML")
  parser.add_argument("--output", default="infra-as-code/kubernetes/prover_pod_unit.rendered.yaml", help="Output YAML")
  parser.add_argument("--image", required=True, help="Container release tag or 'default'")
  parser.add_argument(
      "--radix",
      type=int,
      default=16,
      help="Reduction tree radix (fan-in per node). Default 16 — the real "
           "workload radix (shallow trees at real N: 100→depth 2, 500→depth 3) "
           "matching the prover-node CLI default (issue #310). Pass --radix 2 for "
           "the tiny smoke / back-compat path; radix-2 stays fully supported.",
  )
  parser.add_argument(
      "--leaf-count",
      type=int,
      default=0,
      help="Total number of leaf proofs N (decoupled from radix). Defaults to "
           "radix for back-compat with the single-level (N == radix) pipeline.",
  )
  parser.add_argument("--benchmark-id", default="", help="Benchmark ID for GCS path isolation")
  # ── Fungible-pool path (issue #302): emit the KEDA-autoscaled
  #    `prover-node work --transport=pubsub` Deployment + ScaledObject instead of
  #    the phase-locked per-level Indexed Jobs. This is the FUNGIBLE-AUTOSCALED
  #    orchestration; the default (no --emit-fungible) keeps emitting the
  #    phase-locked per-level Job path (#293/#297). Both are valid; see
  #    infra-as-code/kubernetes/README.md.
  parser.add_argument(
      "--emit-fungible",
      action="store_true",
      help="Emit the fungible-pool Deployment + KEDA ScaledObject (autoscaled "
           "prover-node work) instead of the phase-locked per-level Jobs.",
  )
  parser.add_argument("--topic", default="", help="(fungible) Pub/Sub topic id for follow-on fold descriptors")
  parser.add_argument("--subscription", default="", help="(fungible) Pub/Sub subscription id the pool pulls work from")
  parser.add_argument("--baseload", type=int, default=6, help="(fungible) baseload replicas (KEDA min; ~60%% of peak parallel width, always-on)")
  parser.add_argument("--burst", type=int, default=80, help="(fungible) burst replicas added on top of baseload (KEDA max = baseload + burst)")
  parser.add_argument("--ack-deadline", type=int, default=180, help="(fungible) Pub/Sub ack deadline seconds (~2xP99; radix-16 fold ~80s on c3d-highcpu-16, live 500-tx run; hardware-dependent, re-derive per instance type)")
  parser.add_argument("--cpu", default="", help="(fungible) CPU request override")
  parser.add_argument("--memory", default="", help="(fungible) Memory request override")
  parser.add_argument("--event-topic", default="", help="(fungible) Pub/Sub topic id for coordinator events")
  parser.add_argument("--event-subscription", default="", help="(fungible) Pub/Sub subscription id for coordinator events")
  args = parser.parse_args()

  if not args.image or args.image.strip() == "":
    sys.exit("ERROR: --image argument is required for Kubernetes deployment manifest rendering.")
  image_tag = args.image.strip()
  if image_tag == "default":
    image_tag = "0.0.3-distributed-proving"

  if not os.path.exists(args.config):
    print(f"Error: Config file {args.config} not found.", file=sys.stderr)
    sys.exit(1)

  try:
    with open(args.config, "rb") as f:
      data = tomllib.load(f)
  except (TypeError, AttributeError):
    with open(args.config, "r", encoding="utf-8") as f:
      data = tomllib.load(f)

  gcs_bucket = data.get("gcp", {}).get("bench", {}).get("bucket", "kunal-scratch-tfstate")
  gsa_email = data.get("gcp", {}).get("target", {}).get("runtime_sa", {}).get("email", "")
  if not gsa_email:
    gsa_email = data.get("gcp", {}).get("target", {}).get("build_sa", {}).get("email", "")

  # Dynamically resolve registry URI from config.toml
  project_id = data.get("gcp", {}).get("defaults", {}).get("project", "kunal-scratch")
  registry_cfg = data.get("gcp", {}).get("registry", {})
  registry_region = registry_cfg.get("region", "us")
  registry_repo = registry_cfg.get("repository", "lighter-prover-iac")
  image_uri = f"{registry_region}-docker.pkg.dev/{project_id}/{registry_repo}/zkp-prover:{image_tag}"

  # ── Fungible-pool path (issue #302) ────────────────────────────────────────
  # When --emit-fungible is set, render the autoscaled Deployment + KEDA
  # ScaledObject and exit, instead of the phase-locked per-level Jobs below.
  if args.emit_fungible:
    # Derive leaf_chunk (transactions per chunk) from config.toml
    pod_cfg = data.get("proving_pod", {})
    defaults = pod_cfg.get("defaults", {})
    arch = args.arch if args.arch else str(defaults.get("arch", "c3d"))
    arch_cfg = pod_cfg.get(arch, {})
    leaf_cfg = arch_cfg.get("leaf_worker", {}) if arch_cfg else {}
    leaf_chunk = int(leaf_cfg.get("chunk_size", 1 if arch in ("c3d", "c4d") else 4)) if leaf_cfg else (1 if arch in ("c3d", "c4d") else 4)
    
    # Extract cpu and memory requests from config.toml
    leaf_cpu = str(leaf_cfg.get("cpu_requests", "30" if arch in ("c3d", "c4d") else "64")) if leaf_cfg else ("30" if arch in ("c3d", "c4d") else "64")
    leaf_mem = str(leaf_cfg.get("memory_requests", "60Gi" if arch in ("c3d", "c4d") else "128Gi")) if leaf_cfg else ("60Gi" if arch in ("c3d", "c4d") else "128Gi")

    # We assume 500 transactions for the benchmark block (block 1042)
    txs_per_block = 500
    leaf_count = txs_per_block // leaf_chunk
    depth = max(tree_depth(leaf_count, args.radix), 1)

    benchmark_id = args.benchmark_id if args.benchmark_id else "none"
    gcs_relative_path = f"benchmark-reports/{benchmark_id}/{image_tag}/{arch}"

    render_redis(args)
    render_fungible(args, project_id, gsa_email, gcs_bucket, image_uri, leaf_chunk, leaf_cpu, leaf_mem)
    render_coordinator(args, project_id, gsa_email, gcs_bucket, image_uri, leaf_chunk, gcs_relative_path, leaf_count, depth)
    render_seeder(args, project_id, gsa_email, gcs_bucket, image_uri, leaf_chunk, gcs_relative_path)
    return

  pod_cfg = data.get("proving_pod", {})
  defaults = pod_cfg.get("defaults", {})
  
  arch = args.arch if args.arch else str(defaults.get("arch", "c3d"))
  arch_cfg = pod_cfg.get(arch, {})
  if not arch_cfg:
    print(f"Warning: No [proving_pod.{arch}] found in {args.config}, using fallbacks.", file=sys.stderr)
    arch_cfg = {}

  leaf_cfg = arch_cfg.get("leaf_worker", {})
  agg_cfg = arch_cfg.get("aggregator", {})

  kube_arch = "arm64" if arch == "c4a" else "amd64"

  leaf_cpu = str(leaf_cfg.get("cpu_requests", "30" if arch in ("c3d", "t2d", "c4d") else "64"))
  leaf_mem = str(leaf_cfg.get("memory_requests", "60Gi" if arch in ("c3d", "c4d") else "128Gi"))
  leaf_chunk = int(leaf_cfg.get("chunk_size", 1 if arch in ("c3d", "c4d") else 4))
  
  # Leaf count N is DECOUPLED from radix (fan-in). For back-compat, when
  # --leaf-count is omitted (0) it defaults to radix (the old single-level
  # N == radix pipeline). For an Indexed leaf Job, completions == N: we prove one
  # leaf per completion index. Parallelism is capped by BLOCKS and by N.
  leaf_count = args.leaf_count if args.leaf_count and args.leaf_count > 0 else args.radix
  if leaf_count < 1:
    sys.exit("ERROR: --leaf-count (or --radix fallback) must be >= 1.")

  completions = leaf_count
  parallelism = min(args.blocks, completions)

  # Dynamic tree geometry: depth = ceil(log_radix(N)); each level L has
  # ceil(N / radix^L) tree-node Jobs. depth == 0 (N == 1) means a lone leaf with
  # no folding — still emit one trivial level-1 Job for a uniform pipeline.
  depth = max(tree_depth(leaf_count, args.radix), 1)

  agg_cpu = str(agg_cfg.get("cpu_requests", "30" if arch in ("c3d", "c4d") else "16"))
  agg_mem = str(agg_cfg.get("memory_requests", "60Gi" if arch in ("c3d", "c4d") else "32Gi"))
  agg_replicas = 1 * args.blocks

  if not os.path.exists(args.input):
    print(f"Error: Input YAML {args.input} not found.", file=sys.stderr)
    sys.exit(1)

  mount_opts = "implicit-dirs"
  if args.benchmark_id:
    # GCS Fuse only-dir option mounts a subdirectory as the root of the volume
    mount_opts += f",only-dir={args.benchmark_id}"

  # Split rendering into Leaf and Tree Jobs
  leaf_rendered = f"""apiVersion: v1
kind: ServiceAccount
metadata:
  name: prover-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: {gsa_email}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: lighter-leaf-worker
  labels:
    app: zkp-prover
    role: leaf-worker
    silicon-arch: {arch}
spec:
  parallelism: {parallelism}
  completions: {completions}
  completionMode: Indexed
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        role: leaf-worker
        silicon-arch: {arch}
    spec:
      serviceAccountName: prover-sa
      nodeSelector:
        role: leaf-worker
        silicon-arch: {arch}
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "zkp-prover"
        effect: "NoSchedule"
      restartPolicy: OnFailure
      containers:
      - name: prover
        image: {image_uri}
        command: ["sh", "-c", "prover-node leaf-worker --chunk-idx $JOB_COMPLETION_INDEX --tx-per-proof {leaf_chunk}"]
        resources:
          limits:
            cpu: "{leaf_cpu}"
            memory: "{leaf_mem}"
          requests:
            cpu: "{leaf_cpu}"
            memory: "{leaf_mem}"
        volumeMounts:
        - name: gcs-volume
          mountPath: /data/reports
      volumes:
      - name: gcs-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: "{gcs_bucket}"
            mountOptions: "{mount_opts}"
"""

  # One Indexed tree-node Job PER LEVEL (1..=depth). At level L the Job runs
  # `nodes_at_level(N, radix, L)` completions, each folding up to `radix` children
  # read from the transport ($JOB_COMPLETION_INDEX -> --node-idx). The level-L
  # binary now derives node geometry from --leaf-count, so the same image folds
  # any level. The final (root) level always has exactly one completion.
  #
  # GKE cross-level ordering (#295, follow-up to #291/#293): Kubernetes batch/v1
  # Jobs have no native inter-Job completion gating, so level L+1 must NOT start
  # before every level-L node proof exists in the shared transport. We resolve
  # this with Cloud Build *sequential gating*: each level is emitted to its own
  # uniquely-named manifest (`...-tree-l{level}.rendered.yaml`, Job
  # `lighter-tree-aggregator-l{level}`) and the orchestrator
  # (`infra-as-code/cloudbuild-distributed.yaml`, ENGINE=gke) applies them one at
  # a time, blocking on `kubectl wait --for=condition=complete` between levels.
  # To keep depth/node-counts a SINGLE source of truth (no second computation in
  # bash), this renderer also writes a machine-readable plan file
  # (`...-tree.plan.env`) the orchestrator sources to drive its loop. The binary
  # already fails fast when a child proof is missing; the `kubectl wait` is the
  # actual gate that enforces ordering on a real cluster.
  level_jobs = []          # combined doc for back-compat / inspection
  level_manifests = {}     # level -> rendered single-Job YAML (per-level files)
  level_node_counts = {}   # level -> nodes_at_level (single source of truth)
  for level in range(1, depth + 1):
    level_nodes = nodes_at_level(leaf_count, args.radix, level)
    level_node_counts[level] = level_nodes
    is_root = (level == depth)
    level_parallelism = min(args.blocks, level_nodes)
    level_yaml = f"""apiVersion: batch/v1
kind: Job
metadata:
  name: lighter-tree-aggregator-l{level}
  labels:
    app: zkp-prover
    role: tree-node
    tree-level: "{level}"
    is-root-level: "{str(is_root).lower()}"
    silicon-arch: {arch}
spec:
  parallelism: {level_parallelism}
  completions: {level_nodes}
  completionMode: Indexed
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        role: tree-node
        tree-level: "{level}"
        silicon-arch: {arch}
    spec:
      serviceAccountName: prover-sa
      nodeSelector:
        role: tree-node
        silicon-arch: {arch}
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "zkp-prover"
        effect: "NoSchedule"
      restartPolicy: OnFailure
      containers:
      - name: aggregator
        image: {image_uri}
        command: ["sh", "-c", "prover-node tree-node --level {level} --node-idx $JOB_COMPLETION_INDEX --radix {args.radix} --leaf-count {leaf_count} --tx-per-proof {leaf_chunk}"]
        resources:
          limits:
            cpu: "{agg_cpu}"
            memory: "{agg_mem}"
          requests:
            cpu: "{agg_cpu}"
            memory: "{agg_mem}"
        volumeMounts:
        - name: gcs-volume
          mountPath: /data/reports
      volumes:
      - name: gcs-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: "{gcs_bucket}"
            mountOptions: "{mount_opts}"
"""
    level_manifests[level] = level_yaml
    level_jobs.append(level_yaml)

  # RootCoordinator Job: harvests + verifies the single root proof at the
  # dynamically-computed root level (the binary derives root_level from
  # --leaf-count, so no level is hardcoded here either).
  root_job = f"""apiVersion: batch/v1
kind: Job
metadata:
  name: lighter-root-coordinator
  labels:
    app: zkp-prover
    role: root-coordinator
    silicon-arch: {arch}
spec:
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        role: root-coordinator
        silicon-arch: {arch}
    spec:
      serviceAccountName: prover-sa
      nodeSelector:
        role: tree-node
        silicon-arch: {arch}
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "zkp-prover"
        effect: "NoSchedule"
      restartPolicy: OnFailure
      containers:
      - name: coordinator
        image: {image_uri}
        command: ["prover-node", "root-coordinator", "--radix", "{args.radix}", "--leaf-count", "{leaf_count}", "--node-idx", "0", "--tx-per-proof", "{leaf_chunk}"]
        resources:
          limits:
            cpu: "{agg_cpu}"
            memory: "{agg_mem}"
          requests:
            cpu: "{agg_cpu}"
            memory: "{agg_mem}"
        volumeMounts:
        - name: gcs-volume
          mountPath: /data/reports
      volumes:
      - name: gcs-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: "{gcs_bucket}"
            mountOptions: "{mount_opts}"
"""

  tree_rendered = "---\n".join(level_jobs) + "---\n" + root_job

  leaf_output = args.output.replace(".rendered.yaml", "-leaf.rendered.yaml")
  tree_output = args.output.replace(".rendered.yaml", "-tree.rendered.yaml")
  root_output = args.output.replace(".rendered.yaml", "-tree-root.rendered.yaml")
  plan_output = args.output.replace(".rendered.yaml", "-tree.plan.env")

  with open(leaf_output, "w", encoding="utf-8") as f:
    f.write(leaf_rendered)
  # Combined tree doc retained for back-compat / human inspection.
  with open(tree_output, "w", encoding="utf-8") as f:
    f.write(tree_rendered)
  # Root coordinator as its own manifest so the orchestrator applies/waits on it
  # after the last tree level completes.
  with open(root_output, "w", encoding="utf-8") as f:
    f.write(root_job)

  # Per-level tree-node manifests with deterministic, loop-targetable names so
  # Cloud Build can apply + `kubectl wait` each level IN ORDER (cross-level gate).
  per_level_outputs = []
  for level in range(1, depth + 1):
    level_output = args.output.replace(".rendered.yaml", f"-tree-l{level}.rendered.yaml")
    with open(level_output, "w", encoding="utf-8") as f:
      f.write(level_manifests[level])
    per_level_outputs.append(level_output)

  # Machine-readable plan file: the SINGLE source of truth for depth/node-counts
  # that the cloudbuild ENGINE=gke loop sources (no second computation in bash).
  # ROOT_LEVEL == depth, so the root proof is `tree_L{ROOT_LEVEL}_N0.proof`.
  root_level = depth
  plan_lines = [
      "# Auto-generated by render_pod_spec.py — do not edit by hand.",
      "# Sourced by infra-as-code/cloudbuild-distributed.yaml (ENGINE=gke) to drive",
      "# the cross-level Job gating loop. Single source of truth for tree geometry.",
      f"TREE_DEPTH={depth}",
      f"ROOT_LEVEL={root_level}",
      f'TREE_LEVELS="{" ".join(str(l) for l in range(1, depth + 1))}"',
      f"LEAF_COUNT={leaf_count}",
      f"RADIX={args.radix}",
      f"ROOT_PROOF_NAME=tree_L{root_level}_N0.proof",
  ]
  for level in range(1, depth + 1):
    plan_lines.append(f"TREE_LEVEL_{level}_NODES={level_node_counts[level]}")
  with open(plan_output, "w", encoding="utf-8") as f:
    f.write("\n".join(plan_lines) + "\n")

  print(
      f"[OK] Dynamically rendered K8s Proving Pod Jobs to {leaf_output}, "
      f"{tree_output}, per-level [{', '.join(per_level_outputs)}], {root_output}, "
      f"and plan {plan_output} (arch={arch}, blocks={args.blocks}, "
      f"radix={args.radix}, leaf_count={leaf_count}, depth={depth}, "
      f"root_level={root_level}, leaf_chunk={leaf_chunk})"
  )


if __name__ == "__main__":
  main()
